{% set name = "py4D-browser" %}
{% set version = "0.999" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py4D_browser-{{ version }}.tar.gz
  sha256: 9ceff4b853b7cf4fed3bd52fba8e9d9bda32c05f627efc7bf32d9bea4fa90e11

build:
  entry_points:
    - py4DGUI = py4D_browser.runGUI:launch
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - py4dstem >=0.14.0
    - numpy >=1.19
    - matplotlib-base >=3.2.2
    - pyqt >=5.10
    - pyqtgraph >=0.11

test:
  imports:
    - py4D_browser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/py4dstem/py4D-browser
  summary: A 4D-STEM data browser built on py4DSTEM.
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sezelt
