{% set name = "py4D-browser" %}
{% set version = "0.999995" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py4D_browser-{{ version }}.tar.gz
  sha256: be40edb0f77fe6d00994bbd99a167377ffbdf50580410341dc8db87480d3b04f

build:
  entry_points:
    - py4DGUI = py4D_browser.runGUI:launch
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - py4dstem >=0.14.3
    - h5py
    - numpy >=1.19
    - matplotlib-base >=3.2.2
    - pyqt >=5.10
    - pyqtgraph >=0.11

test:
  imports:
    - py4D_browser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/py4dstem/py4D-browser
  summary: A 4D-STEM data browser built on py4DSTEM.
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sezelt
